{% set name = "yeadon" %}
{% set version = "1.5.0" %}
{% set sha256 = "3bd50c5eecd41410eebda88d45332385817f9284b30b2866ca5cd21503623867" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools >=44.1.1
    - pip
  run:
    - python
    - numpy >=1.21.5
    - pyyaml >=5.4.1
  run_constrained:
    - mayavi >=4.7.1

test:
  files:
    - ice_skating.py
    - male1.txt
    - import_test.py
  commands:
    - python ice_skating.py
    - python import_test.py

about:
  home: https://github.com/chrisdembia/yeadon/
  doc_url: http://yeadon.readthedocs.org/
  dev_url: https://github.com/chrisdembia/yeadon/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Estimates the inertial properties of a human.'
  description: |
    This package calculates the masses, center of mass positions, and inertia
    tensors that correspond to the human inertia model developed by Yeadon in
    (Yeadon, 1990). The package allows for the input of both measurements and
    configuration variables (joint angles), and provides 3D visualization using
    the MayaVi package.

extra:
  recipe-maintainers:
    - moorepants
    - chrisdembia
