travis:
  secure:
    BINSTAR_TOKEN: UO1pgWU1jbK2WNgHLl2eA2lWehd2naMxyHpr1eWLc/lVnr0sXVQFl2R9MrKAtv12EewWGSi+68rkYScrL9GutaW0UJjDkR4uPgpYD6EZsL3zgHclgDJszagddIODSotyfMsW9IxDzwo5dAnFAp6YJB5OGab5uz19oGD0bMgWzNSKtT8PT0AOj/wkeWsXH5150B1LKaix8ddGS7VS55IphacJEYOcIx3pjKC+k0l5ewUtPGGHnFRu5V29M5vu/LFf5rWFb/G71fRgflase9/yDqNKS74qVodLBz0++tDYoVbfnZmVmIb9FHH7mLkJ8/t2vfuTs0tDR0TsygiILqtdfixEkxYe5fRNJy8BUKNKNh5pZJEBl1axpaPYKTJnHWKoolXVTy1ydOoIuk8jmXw/tLZqWUkLB4K7gRHZ+80x/crZW2WFFZFmQaZ6nUOXPT6qsarAOlYNamL7dTvfhmkI/KEgwpJgUenwqpjgRiGHAuq8ZX3KgGy6zHNpwsmjLNggIoL0ZEd4v1jyhIDKB+7DWsrj1xPQ4ItyA4DHzU8CCGTb4KAViIevpKt3os3BkNaJOlrW0bkEW19bBxVk8/gHkKF519Br+x62LO1MWr8ZC8sMo4YuN3HFMMoDZFBZZU/TT/gVjuMDaH0xieW37Qco6IasHywzwJDxgvN10HYVn9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
